// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQYI0Ad_VITMgZnezu9fICRJyeBCahCP8',
    appId: '1:215450876430:web:90d9b5a9ec64b9205c5a5f',
    messagingSenderId: '215450876430',
    projectId: 'to-do-list-app-0910',
    authDomain: 'to-do-list-app-0910.firebaseapp.com',
    databaseURL: 'https://to-do-list-app-0910-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'to-do-list-app-0910.firebasestorage.app',
    measurementId: 'G-WXYFGTYXHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpJr-Rak1eewCq4dcaoAbM9aiGKkpa2UA',
    appId: '1:215450876430:android:94fd0bd173d91a845c5a5f',
    messagingSenderId: '215450876430',
    projectId: 'to-do-list-app-0910',
    databaseURL: 'https://to-do-list-app-0910-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'to-do-list-app-0910.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC59OZWfGKVg08kw2OfJAe7JgNEhx6DHgA',
    appId: '1:215450876430:ios:6a10fbc62df2ab195c5a5f',
    messagingSenderId: '215450876430',
    projectId: 'to-do-list-app-0910',
    databaseURL: 'https://to-do-list-app-0910-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'to-do-list-app-0910.firebasestorage.app',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC59OZWfGKVg08kw2OfJAe7JgNEhx6DHgA',
    appId: '1:215450876430:ios:6a10fbc62df2ab195c5a5f',
    messagingSenderId: '215450876430',
    projectId: 'to-do-list-app-0910',
    databaseURL: 'https://to-do-list-app-0910-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'to-do-list-app-0910.firebasestorage.app',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQYI0Ad_VITMgZnezu9fICRJyeBCahCP8',
    appId: '1:215450876430:web:b7eb5e978bced9ad5c5a5f',
    messagingSenderId: '215450876430',
    projectId: 'to-do-list-app-0910',
    authDomain: 'to-do-list-app-0910.firebaseapp.com',
    databaseURL: 'https://to-do-list-app-0910-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'to-do-list-app-0910.firebasestorage.app',
    measurementId: 'G-7NCDF7N1LB',
  );
}
